const constants = require("./constants");
const SERVER_URL = constants.SERVER_URL;

const PW_CERTIFICATE_TEMPLATES = [
  {
    TEMPLATE_ID: "PW_T01",
    TITLE: "CERTIFICATE 1",
    STUDENT_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    COURSE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    START_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    END_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    QR_CODE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_LOGO: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_INSTITUTE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_SIGNATURE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    TEMPLATE_PATH: SERVER_URL + "PW_CERTIFICATE_TEMP_01.png",
  },

  {
    TEMPLATE_ID: "PW_T02",
    TITLE: "CERTIFICATE 2",
    STUDENT_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    COURSE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    START_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    END_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    QR_CODE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_LOGO: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_INSTITUTE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_SIGNATURE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    TEMPLATE_PATH: SERVER_URL + "PW_CERTIFICATE_TEMP_02.png",
  },

  {
    TEMPLATE_ID: "PW_T03",
    TITLE: "CERTIFICATE 3",
    STUDENT_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    COURSE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    START_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    END_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    QR_CODE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_LOGO: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_INSTITUTE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_SIGNATURE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    TEMPLATE_PATH: SERVER_URL + "PW_CERTIFICATE_TEMP_03.png",
  },

  {
    TEMPLATE_ID: "PW_T04",
    TITLE: "CERTIFICATE 4",
    STUDENT_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    COURSE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    START_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    END_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    QR_CODE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_LOGO: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_INSTITUTE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_SIGNATURE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    TEMPLATE_PATH: SERVER_URL + "PW_CERTIFICATE_TEMP_04.png",
  },

  {
    TEMPLATE_ID: "PW_T05",
    TITLE: "CERTIFICATE 5",
    STUDENT_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    COURSE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    START_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    END_DATE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    QR_CODE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_LOGO: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_INSTITUTE_NAME: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    CUSTOMER_SIGNATURE: [{ X_AXIS: 123, Y_AXIS: 2.2 }],
    TEMPLATE_PATH: SERVER_URL + "PW_CERTIFICATE_TEMP_05.png",
  },
];

module.exports = {
  PW_CERTIFICATE_TEMPLATES,
};
